[workspace]
members = ["crates/stormd", "crates/stormlog", "crates/stormsh"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.8", features = ["ws"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "trace"] }
thiserror = "2"
anyhow = "1"
cron = "0.13"
async-nats = "0.38"
clap = { version = "4", features = ["derive"] }
flate2 = "1"
tar = "0.4"
tokio-util = { version = "0.7", features = ["io"] }
vt100 = "0.15"
rust-s3 = { version = "0.35", default-features = false, features = ["tokio-rustls-tls"] }
ratatui = "0.29"
crossterm = "0.28"
russh = "0.46"
russh-keys = "0.46"
tokio-tungstenite = { version = "0.24", features = ["rustls-tls-webpki-roots"] }
futures-util = "0.3"
async-trait = "0.1"
stormpull = { git = "https://github.com/gwest/stormbase", path = "crates/stormpull" }
oci-spec = "0.7"
sha2 = "0.10"
hex = "0.4"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
